services:

  _defaults:
    public:        false
    autowire:      true
    autoconfigure: true

  app.cache.default:
    alias:  Symfony\Component\Cache\Adapter\ArrayAdapter

  Symfony\Component\Cache\Adapter\ArrayAdapter: ~