services:

    _defaults:
        autowire:      true
        autoconfigure: true
        public:        false

    Eureka\Component\Password\:
        resource: '../../vendor/eureka/component-password/src'

    Eureka\Component\Web\:
        resource: '../../vendor/eureka/component-web/src'

    session:
        alias: Eureka\Component\Web\Session\Session
