# Services Yaml file
parameters:

    eureka.deployer.dir.src: '/data/src'
    eureka.deployer.dir.www: '/data/www'

    eureka.deployer.config:
        # Default values
        app.name:   '%app.name%'
        app.tag:    '%app.version%'
        app.domain: 'www.%app.name%.com'

        install:
            #~ Installation steps
            step.start: 0
            step.end:   100

            step.list:
                #~ 0: Start Install (defined in main install script)
                #~ 1 to 9: reserved for deployed itself
                #~ 001: Install composer
                #~ 002: Copy secrets files

                #~ Setup some directories
                10: 'Install/Init/Directories'

                #~ Cleaning installation files
                70: 'Install/Clean/Files'

                #~ Composer cleaning & install no-dev
                80: 'Install/Clean/Cache'

                #~ 90 to 99: reserved for deployed itself

                #~ 100: Ending installation (defined in main install script)

            init:
                directories:
                    'var/log':   777
                    'var/cache': 777
                    'var/test':  777

            copy:
                files:
                    '/data/conf/{platform}/{domain}/database.yaml': 'config/secrets/database.yaml'

            clean:
                files:
                    - '.gitignore'
                    - 'README.md'

                directories:
                    - 'sql/'


services:
    # default configuration for services in *this* file
    _defaults:
        public:        false
        autowire:      true
        autoconfigure: true

    Eureka\Component\Deployer\:
        resource: '../../vendor/eureka/component-deployer/src/*'
        exclude:  '../../vendor/eureka/component-deployer/src/{Script}'

    Eureka\Component\Deployer\Script\:
        resource: '../../vendor/eureka/component-deployer/src/Script/*'
        public: true
        calls:
            - ['setPathBuilder']

    Eureka\Component\Deployer\Common\PathBuilder:
        arguments:
            $pathSource: '%eureka.deployer.dir.src%'
            $pathLink:   '%eureka.deployer.dir.www%'
