parameters:

  menu.cookie_state_name: 'menu_state'

  menu.config.left:

    home:
      label: 'Dashboard'
      icon: 'bi bi-speedometer'
      route: 'home'
      children: ~

    menu_ui:
      label: 'UI Elements'
      icon: 'bi bi-tree-fill'
      route: '#'
      children:
        - label: 'General'
          route: 'web_page'
          route_params: { page: 'ui-general' }
        - label: 'Timeline'
          route: 'web_page'
          route_params: { page: 'ui-timeline' }

    menu_widgets:
      label: 'Widgets'
      icon: 'bi bi-box-seam-fill'
      route: '#'
      children:
        - label: 'Small box'
          route: 'web_page'
          route_params: { page: 'widgets-small-box' }
        - label: 'Info box'
          route: 'web_page'
          route_params: { page: 'widgets-info-box' }
        - label: 'Card'
          route: 'web_page'
          route_params: { page: 'widgets-card' }

    menu_forms:
      label: 'Forms'
      icon: 'bi bi-pencil-square'
      route: '#'
      children:
        - label: 'Generals Elements'
          route: 'web_page'
          route_params: { page: 'forms-general' }

    menu_tables:
      label: 'Tables'
      icon: 'bi bi-table'
      route: '#'
      children:
        - label: 'Simple Tables'
          route: 'web_page'
          route_params: { page: 'tables-simple' }

  menu.config.right: [ ]
