parameters:

    meta.config:
        title:   'Eureka'
        charset: 'utf-8'

        app:
            name_short: ''
            name_full: 'Eureka Backoffice'

        description: 'This application is an template backoffice application based on Eureka Framework component'
        keywords:    'eureka, backoffice, template, component, php, framework'
        author:      'Romain Cottard'
        version:     '%app.version%'

        copyright:
            year: 'now'
            name: 'Romain Cottard'

        footer:
            links: []

        #~ Other meta data

        social:
            facebook: '#'
            twitter:  'https://twitter.com/velkuns'
            feed:     '#'
