parameters:

  app.middleware:
    timeLogger:     'Eureka\Kernel\Http\Middleware\ResponseTimeLoggerMiddleware'
    errorWeb:       'Eureka\Kernel\Http\Middleware\ErrorMiddleware'
    errorApi:       'Application\Middleware\ErrorApiMiddleware'
    twig:           'Application\Middleware\TwigMiddleware'
    router:         'Eureka\Kernel\Http\Middleware\RouterMiddleware'
    rateLimiter:    'Eureka\Kernel\Http\Middleware\RateLimiterMiddleware'
    authentication: 'Application\Middleware\AuthenticationMiddleware'
    controller:     'Eureka\Kernel\Http\Middleware\ControllerMiddleware'

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true
    autoconfigure: true
    public: true
    bind:
      $applicationName: '%app.name%'
      $cache:           '@app.cache.default'

  #~ Global Kernel Services Middleware
  Eureka\Kernel\Http\Middleware\:
    resource: '../../vendor/eureka/kernel-http/src/Middleware'

  #~ Global Application Services Middleware
  Application\Middleware\:
    resource: '../../src/Middleware'

  Application\Middleware\TwigMiddleware:
    arguments:
      $twigPaths:     '%twig.paths%'
      $webAssetsPath: '%app.web.assets.path%'

  #~ Error middleware for classic web application
  Eureka\Kernel\Http\Middleware\ErrorMiddleware:
    arguments:
      $errorController: '@Application\Controller\Web\Error\ErrorController'

  #~ Error middleware for api part of the application
  Application\Middleware\ErrorApiMiddleware:
    arguments:
      $errorController: '@Application\Controller\Api\Error\ErrorController'
