parameters:

  #~ Comment part
  orm.comment.author:    'Eureka Orm Generator'
  orm.comment.copyright: 'Romain Cottard'

  #~ Namespace base config
  orm.base_namespace.entity:     'Application\Domain'
  orm.base_namespace.mapper:     'Application\Domain'
  orm.base_namespace.repository: 'Application\Domain'

  #~ Path base config
  orm.base_path.entity:     '%kernel.directory.root%/src/Domain'
  orm.base_path.mapper:     '%kernel.directory.root%/src/Domain'
  orm.base_path.repository: '%kernel.directory.root%/src/Domain'

  #~ Cache base config
  orm.cache.enabled: false
  orm.cache.prefix: 'application.'

  #~ Validation
  orm.validation.enabled: true
  orm.validation.auto:    true

  #~ Subdomain config
  orm.config.subdomain.common: 'Common'

  #~ Configs
  orm.configs:
    user: '%orm.config.user%'

services:
  _defaults:
    autowire: true

  Eureka\Component\Orm\:
    resource: '../../vendor/eureka/component-orm/src/*'
    exclude:  '../../vendor/eureka/component-orm/src/{Script}'

  ######################################################################################################################
  # Eureka ORM
  ######################################################################################################################
  Eureka\Component\Validation\:
    resource: '../../vendor/eureka/component-validation/src/*'


  ######################################################################################################################
  # ORM Script generator
  ######################################################################################################################
  Eureka\Component\Orm\Script\Generator:
    public: true
    arguments:
      $ormConfigs: '%orm.configs%'
