# For route with log-in needed, add following parameter in defaults: "authenticationRequired: true"
# ======================================================================================================================
# =                                                 WEB                                                                =
# ======================================================================================================================
home:
    path: /
    controller: Application\Controller\Web\Home\HomeController::index
    methods: [ GET ]
    defaults:
        authenticationRequired: true

# ======================================================================================================================
# =                                               DEMO PAGES                                                           =
# ======================================================================================================================
web_page:
    path: /page/{page}
    controller: Application\Controller\Web\Page\PageController::index
    methods: [ GET ]
    requirements:
        page: '[a-z-]+'
    defaults:
        authenticationRequired: true

# ======================================================================================================================
# =                                                LOGIN                                                               =
# ======================================================================================================================
user_login:
    path: /user/login
    controller: Application\Controller\Web\User\LoginController::view
    methods: [ GET ]

user_signin:
    path: /user/signin
    controller: Application\Controller\Web\User\LoginController::signIn
    methods: [ POST ]


# ======================================================================================================================
# =                                                 API                                                                =
# ======================================================================================================================
#api_home:
#  path: /api/
#  controller: Application\Controller\Api\Home\HomeController::index
#  methods: [ GET ]
#
