# Services Yaml file
parameters:
  app.name: 'eureka'
  app.version: '1.0.0'

services:
  Psr\Container\ContainerInterface:
    alias: 'service_container'
    # ...

  Symfony\Component\AssetMapper\Command\ImportMapInstallCommand:
    tags:
      - { name: 'console.command', command: 'importmap:install' }
